include:
  - board: seeeduino_xiao_ble
    shield: charybdis_dongle

  - board: nice_nano_v2
    shield: charybdis_left

  - board: nice_nano_v2
    shield: charybdis_right

  - board: seeeduino_xiao_ble
    shield: settings_reset
    
  - board: nice_nano_v2
    shield: settings_reset
